#Game Settings
WIDTH = 1280
HEIGHT = 720
FPS = 60



#Player settings
PLAYER_START_X = 300
PLAYER_START_Y = 300
PLAYER_SPEED = 22
PLAYER_SIZE = 0.6
PLAYER_HEALTH = 7
PLAYER_SHOOT_COOLDOWN = 15

#bullet settings
ENEMY_SHOOT_COOLDOWN = 15
BULLET_SPEED = 60
BULLET_IMAGE = r".\Assets\bullet\bullet.png"
BULLET_SIZE = 0.1
BULLET_RANGE = 1000
BULLET_DAMAGE = 1

#grenade settings
GRENADE_SIZE = 0.3
GRENADE_IMAGE = r".\Assets\grenade.png"
GRENADE_RANGE_MIN = 250
GRENADE_SPEED =30
GRENADE_FUSE = 37
GRENADE_RADIUS = 50
GRENADE_DAMAGE = 3
GRENADE_COOLDOWN = 120

#explosion settings
EXPLOSION_IMAGE_PATH = r".\Assets\explosion"
EXPLOSION_SCALE = 3

#enemy settings
NORMAL_ENEMY_RANGE = 1000
NORMAL_ENEMY_IMAGE = r".\Assets\enemies\enemy_type_normal.png"
NORMAL_ENEMY_SIZE = 0.5             
NORMAL_ENEMY_SPEED = 15             
NORMAL_ENEMY_HEALTH = 5             
NORMAL_ENEMY_DAMAGE = 1

BRUTE_ENEMY_IMAGE = r".\Assets\enemies\enemy_type_brute.png"
BRUTE_ENEMY_SIZE = 0.5 
BRUTE_ENEMY_SPEED = 13
BRUTE_ENEMY_HEALTH = 10 
BRUTE_ENEMY_RANGE = 1000
BRUTE_OUT_OF_RANGE_TIMER = 120
BRUTE_ENEMY_DAMAGE = 2
BRUTE_ENEMY_GRENADE_COOLDOWN = 120


BOSS_ENEMY_SIZE = 0.5
BOSS_ENEMY_IMAGE = r".\Assets\enemies\venn_the_slayer.png"
BOSS_ENEMY_HEALTH = 20
BOSS_ENEMY_DAMAGE = 3
BOSS_ENEMY_GRENADE = 3
BOSS_ENEMY_SPEED = 17
BOSS_ENEMY_RANGE = 2000
BOSS_ENEMY_GRENADE_COOLDOWN = 30
BOSS_ENEMY_OUT_OF_RANGE_TIMER = 30
BOSS_ENEMY_SHOOT_COOLDOWN = 5


PATHFIND_COOLDOWN = 60


#MTC 
MTC_LOGO = r"Assets/mtcbpdc_logo.jpeg"
MTC_WIDTH = 100
MTC_HEIGHT = 100


#SFX
SHOOT_SOUND = r".\Assets\sfx\laser.mp3"
HIT_SOUND = r".\Assets\sfx\hit_soundeffect.wav"
EXPLOSION_SOUND = r".\Assets\sfx\explosion.mp3"

#zoom
ZOOM = 0.5